          #:schema https://raw.githubusercontent.com/policastro/mondrian/refs/heads/main/assets/configs/mondrian.schema.json

[general]
allow_focus_on_empty_monitor = true # if true, the focus action will also consider empty monitors  
animations.duration = 150  # duration of the animation in milliseconds
animations.enabled = true # enables or disables the animations
animations.framerate = 144 # animations framerate
animations.type = "ease_out_back" # can be "linear" or any of the easings functions from https://easings.net/ (in snake_case)
auto_reload_configs = true # if true, the config will be reloaded when a change is detected
default_workspace = "1" # default workspace
detect_maximized_windows = true # if true, maximized windows will be detected and they will not be managed by the tiling engine
floating_wins.centered = true # if true, floating windows are centered on the monitor when released
floating_wins.size = "relative" # how floating windows are resized
floating_wins.size_fixed = [700, 400] # fixed size of the floating window 
floating_wins.size_ratio = [
    0.5,
    0.5,
] # ratio of the floating window's size relative to the monitor 
floating_wins.topmost = true # if true, floating windows are always on top of other windows
free_move_in_monitor = false # if true, when the window is inserted in a new monitor, the position will determined by where the mouse is
history_based_navigation = true # if true, the navigation will prioritize the focus history
insert_in_monitor = true # if true, when the window is moved to a new monitor, it will be inserted instead of being swapped
move_cursor_on_focus = true # if true, the cursor will be moved to the center of the focused window

[layout]
focalized_padding = 8                # padding for the focalized window, it must be between 0 and 120
half_focalized_paddings.borders = 18 # padding between border and tiles for the half-focalized windows, it must be between 0 and 100
half_focalized_paddings.tiles = 12   # padding between tiles for the half-focalized windows, it must be between 0 and 100 
paddings.borders = 8                # padding between border and tiles, it must be between 0 and 100
paddings.tiles = 4                   # padding between tiles, it must be between 0 and 100 
tiling_strategy = "twostep"     # can be "golden_ratio", "horizontal", "vertical", "twostep" or "squared"

[layout.strategy.golden_ratio] # if tiling_strategy = "golden_ratio"
clockwise = true # true = clockwise, false = counterclockwise
ratio = 65       # ratio of the first split
vertical = false # if true, the first split will be vertical

[layout.strategy.horizontal] # if tiling_strategy = "horizontal"
grow_right = true # if true, new windows will be placed on the right side of the screen

[layout.strategy.vertical] # if tiling_strategy = "vertical"
grow_down = true # if true, new windows will be placed on the bottom side of the screen

[layout.strategy.twostep] # if tiling_strategy = "twostep"
first_step = "right" # first insertion direction, can be <"right"|"left"|"up"|"down">
ratio = 65           # ratio of the first split
second_step = "down" # second insertion direction, can be <"right"|"left"|"up"|"down">

[modules.keybindings]
enabled = true # enables or disables the keybindings module
bindings = [
    # Navigation
    { modifiers = "ALT", key = "left", action = "focus left" },
    { modifiers = "ALT", key = "right", action = "focus right" },
    { modifiers = "ALT", key = "up", action = "focus up" },
    { modifiers = "ALT", key = "down", action = "focus down" },

    { modifiers = "ALT", key = "h", action = "focus left" },
    { modifiers = "ALT", key = "l", action = "focus right" },
    { modifiers = "ALT", key = "k", action = "focus up" },
    { modifiers = "ALT", key = "j", action = "focus down" },

    # Insert
    { modifiers = "SHIFT+ALT", key = "left", action = "moveinsert left" },
    { modifiers = "SHIFT+ALT", key = "right", action = "moveinsert right" },
    { modifiers = "SHIFT+ALT", key = "up", action = "moveinsert up" },
    { modifiers = "SHIFT+ALT", key = "down", action = "moveinsert down" },

    { modifiers = "SHIFT+ALT", key = "h", action = "moveinsert left" },
    { modifiers = "SHIFT+ALT", key = "l", action = "moveinsert right" },
    { modifiers = "SHIFT+ALT", key = "k", action = "moveinsert up" },
    { modifiers = "SHIFT+ALT", key = "j", action = "moveinsert down" },

     # Insert
    { modifiers = "CTRL+SHIFT+ALT", key = "left", action = "insert left" },
    { modifiers = "CTRL+SHIFT+ALT", key = "right", action = "insert right" },
    { modifiers = "CTRL+SHIFT+ALT", key = "up", action = "insert up" },
    { modifiers = "CTRL+SHIFT+ALT", key = "down", action = "insert down" },

    { modifiers = "CTRL+SHIFT+ALT", key = "h", action = "insert left" },
    { modifiers = "CTRL+SHIFT+ALT", key = "l", action = "insert right" },
    { modifiers = "CTRL+SHIFT+ALT", key = "k", action = "insert up" },
    { modifiers = "CTRL+SHIFT+ALT", key = "j", action = "insert down" },

    # Resize
    { modifiers = "CTRL+ALT", key = "left", action = "resize left 150" },
    { modifiers = "CTRL+ALT", key = "right", action = "resize right 150" },
    { modifiers = "CTRL+ALT", key = "up", action = "resize up 150" },
    { modifiers = "CTRL+ALT", key = "down", action = "resize down 150"},
    
    { modifiers = "CTRL+ALT", key = "h", action = "resize left 150" },
    { modifiers = "CTRL+ALT", key = "l", action = "resize right 150" },
    { modifiers = "CTRL+ALT", key = "k", action = "resize up 150" },
    { modifiers = "CTRL+ALT", key = "j", action = "resize down 150" },
    # Workspaces
    { modifiers = "ALT", key = "1", action = "focus-workspace 1" },
    { modifiers = "ALT", key = "2", action = "focus-workspace 2" },
    { modifiers = "SHIFT+ALT", key = "1", action = "move-to-workspace 1" },
    { modifiers = "SHIFT+ALT", key = "2", action = "move-to-workspace 2" },
    # Others
    { modifiers = "ALT", key = "r", action = "release" },
    { modifiers = "ALT", key = "f", action = "focalize" },
    { modifiers = "ALT", key = "m", action = "minimize" },
    { modifiers = "ALT", key = "v", action = "invert" },
    { modifiers = "ALT+SHIFT", key = "p", action = "pause" },
    { modifiers = "ALT+CTRL+SHIFT", key = "i", action = "dumpstateinfo" },
]

[modules.overlays]
active.color = "#FFFFFF"         # color of the border, as [r, g, b]/[r, g, b, a] or as hex string ("#rrggbb"/"#rrggbbaa")
active.enabled = true            # shows the active overlay
border_radius = 3               # border radius
enabled = true                   # enables or disables the overlays module
floating.color = "#DCC6E0"       # color of the border, as [r, g, b]/[r, g, b, a] or as hex string ("#rrggbb"/"#rrggbbaa")
floating.enabled = true          # shows the floating overlay
focalized.color = "#FFFFFF"      # color of the border, as [r, g, b]/[r, g, b, a] or as hex string ("#rrggbb"/"#rrggbbaa")
focalized.enabled = true         # shows the focalized overlay
half_focalized.color = "#DCF2D7" # color of the border, as [r, g, b]/[r, g, b, a] or as hex string ("#rrggbb"/"#rrggbbaa")
half_focalized.enabled = true    # shows the half-focalized overlay
inactive.color = "#696969"       # color of the border, as [r, g, b]/[r, g, b, a] or as hex string ("#rrggbb"/"#rrggbbaa")
inactive.enabled = true          # shows the inactive overlays
padding = 0                      # padding between the overlay and the window
thickness = 1                    # thickness of the border
update_while_animating = true    # the overlays will be updated while the animation is running 
update_while_dragging = true     # the overlays will be updated while dragging the window

[core]
ignore_rules = [
    { exename = "OpenWith.exe" },                                                                    # "Open with" dialog 
    { exename = "StartMenuExperienceHost.exe" },                                                     # Manages the start menu
    { classname = "OperationStatusWindow" },                                                         # Explorer operation status 
    { title = "/[Pp]icture.in.[Pp]icture/", classname = "/Chrome_WidgetWin_1|MozillaDialogClass/" }, # PIP Firefox/Chrome
]

# Custom rules
#rules = [
#    { filter = { classname = "#32770" }, behavior.float = { size = "preserve" } },
#]

# Monitors configuration
#[monitors."MONITOR1"]
#layout.tiling_strategy = "horizontal"

# Workspaces configuration
#[workspaces."1"]
#layout.tiling_strategy = "horizontal"
